"""Initial migration

Revision ID: 289f9b2dc8c5
Revises: 
Create Date: 2025-05-10 21:20:57.485322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289f9b2dc8c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('shard_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.String(length=255), nullable=True),
    sa.Column('state_type', sa.String(length=100), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('parent_event_id', sa.Integer(), nullable=True),
    sa.Column('context_version', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('attr_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wf_events', 'workflow_events', ['run_id', 'event_id'], unique=False)
    op.create_index('idx_wf_events_shard', 'workflow_events', ['shard_id', 'run_id', 'event_id'], unique=False)
    op.create_table('workflow_templates',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('dsl_definition', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('workflow_visibility',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('workflow_type', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('search_attrs', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_visibility_status', 'workflow_visibility', ['status'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('shard_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=20), server_default=sa.text("'sync'"), nullable=False),
    sa.Column('current_state_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('workflow_type', sa.String(length=255), nullable=False),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('input_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('result_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('current_event_id', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('search_attrs', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.template_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_wf_shard_status', 'workflow_executions', ['shard_id', 'status'], unique=False)
    op.create_table('activity_tasks',
    sa.Column('task_token', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('shard_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=255), nullable=False),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_policy', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_executions.run_id'], ),
    sa.PrimaryKeyConstraint('task_token')
    )
    op.create_index('idx_activity_run_seq', 'activity_tasks', ['run_id', 'seq'], unique=False)
    op.create_index('idx_activity_status', 'activity_tasks', ['status'], unique=False)
    op.create_table('timers',
    sa.Column('timer_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('shard_id', sa.Integer(), nullable=False),
    sa.Column('fire_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_executions.run_id'], ),
    sa.PrimaryKeyConstraint('timer_id')
    )
    op.create_index('idx_timers_run', 'timers', ['run_id', 'fire_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timers_run', table_name='timers')
    op.drop_table('timers')
    op.drop_index('idx_activity_status', table_name='activity_tasks')
    op.drop_index('idx_activity_run_seq', table_name='activity_tasks')
    op.drop_table('activity_tasks')
    op.drop_index('idx_wf_shard_status', table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index('idx_visibility_status', table_name='workflow_visibility')
    op.drop_table('workflow_visibility')
    op.drop_table('workflow_templates')
    op.drop_index('idx_wf_events_shard', table_name='workflow_events')
    op.drop_index('idx_wf_events', table_name='workflow_events')
    op.drop_table('workflow_events')
    # ### end Alembic commands ###
